name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  installation:
    uses: ./.github/workflows/init.yml
  build:
    runs-on: self-hosted
    needs: installation
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags:  qualite863/iblog-frontend:latest
