name: "Linter"

on:
  pull_request:
    branches-ignore:
      - 'temp/**'
      - 'dependabot/**'

  push:
    branches-ignore:
      - 'temp/**'

jobs:
  installation:
    uses: ./.github/workflows/init.yml
  linter:
    runs-on: self-hosted
    steps:
      - uses: super-linter/super-linter@v7.3.0
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_MARKDOWN: true
          VALIDATE_HTML: true
          VALIDATE_YAML: true
          VALIDATE_CSS: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_JSON: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
