name: "Release"

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master


jobs:
  installation:
    uses: ./.github/workflows/init.yml
  test:
    if: github.actor != 'dependabot[bot]'
    runs-on: self-hosted
    needs: installation
    steps:
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
