name: "Test"

on:
  pull_request:
    branches-ignore:
      - 'temp/**'
  push:
    branches-ignore:
      - 'temp/**'


jobs:
  installation:
    uses: ./.github/workflows/init.yml
  test:
    if: github.actor != 'dependabot[bot]'
    runs-on: runner
    needs: installation
    steps:
      - run: yarn test
